# Generated by Django 5.1.6 on 2025-09-17 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
