# Generated by Django 5.1.6 on 2025-09-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_medicalhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='date_diagnosed',
        ),
    ]
